Ting som ikke er med:

- Sletting og insetting av elementer og rader.

# Todimensjonale numpy-arrays

Noe av det som er veldig praktisk med numpy-arrays er at det går an å lage de i flere dimensjoner. Det er kanskje her numpy-arrays virkelig overgår de vanlig python-listene. I denne øvingen skal vi se litt på hvordan man lager numpy-arrays med 2 dimensjoner og hva disse kan brukes til.

## Oppretting av todimensjonale numpy-arrays

Det er ikke så mye vanskeligere å opprette todimensjonale numpy-arrays enn endimensjonale. En mulig måte å gjøre det på er å sende inn en todimensjonal python-liste som vist under. Legg merke til hvordan numpy-arrayen blir printet ut på en mye penere måte enn python-lista.

***Kjør kodeblokken under og se hva den gjør***

In [1]:
import numpy as np

python_liste = [[7, 3.14, 5, 8],
                [3, 9, 7 ,13],
                [4, 5, 2.73, 9]]

numpy_array = np.array([[7, 3.14, 5, 8],
                        [3, 9, 7 ,13],
                        [4, 5, 2.73, 9]])

print(python_liste)
print("\n--------------------------------------------\n")
print(numpy_array)

ModuleNotFoundError: No module named 'numpy'

Det som er verdt å merke seg er at en todimensjonal numpy-array alltid må være MxN stor. Det er alltid like mange elementer i hver rad og like mange elementer i hver kolonne, altså alltid fulle tabeller. Hvis vi prøver å lage en numpy-array uten at det er like mange elementer i hver rad vil numpy lagre det som en *endimensjonal numpy-array med lister*. Dette har vi et eksempel på under. Endimensjonale numpy-arrays med lister blir helt håpløse å jobbe med og er overhodet ikke anbefalt.

In [ ]:
# Ikke gjør dette her'a, plis
import numpy as np
numpy_array = np.array([[7, 3.14, 5, 8],
                        [3, 9, 7], # Denne raden mangler et element
                        [4, 5, 2.73, 9]])
print(numpy_array)

Hvis vi skal finne ut størrelsen på en array må vi bruke attributten `shape` (uten parenteser!). Denne vil gi en tuppel med størrelsen til arrayen, hvor tuppelen har et element per dimensjon. Hvis vi for eksempel har en todimensjonal array vil vi få en tuppel med to verdier hvor den ene er antall rader og den andre antall kolonner. Dette vises i eksempelet under:

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6],              
              [7, 8]])
print(a.shape)
print("Antall rader:", a.shape[0])
print("Antall kolonner:", a.shape[1])

Det finnes også flere måter å opprette numpy-arrays på, og et utvalg av disse kan du se i eksempelet under. Det burde være ganske greit å skjønne hva funksjonene gjør, og hvis du ikke skjønner det er det mulig å teste ut med andre verdier og kjøre koden på nytt. I tillegg finnes den ofisielle listen for hvordan man kan lage arrays [her](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html).

***Kjør koden under og se om du skjønner hva de forskjellige funksjonene gjør***

In [ ]:
import numpy as np

print("----------ones------------\n")
print(np.ones((3, 4)))

print("\n----------zeros-----------\n")
print(np.zeros((2, 3), dtype=np.int16)) # Prøv å fjerne ", dtype=np.int16" og se hva som skjer

print("\n----------random----------\n")
print(np.random.random((2, 2)))

print("\n----------full------------\n")
print(np.full((2, 4), 7))

print("\n----------eye-------------\n")
print(np.eye(8)) # Denne vil dere lære mer om i matte 3 og kan være nyttig

Det er også mulig å lage en todimensjonal array ut av en endimensjonal array ved hjelp av `reshape`-funksjonen. **OBS:** Her må antall rader og antall kolonner gå opp med antall elementer i arrayen man bruker reshape på. 

Prøv å endre koden under og se om du kan gjøre om `a` til en annen form enn `(3, 4)`:

In [ ]:
import numpy as np

a = np.arange(1, 13, 1) # Denne arrayen får 12 elementer

a = np.reshape(a, (3,4))
# kunne også skrevet: a = a.reshape((3,4))

print(a)

## Aksessering av todimensjonale numpy-arrays

Aksessering av todimensjonale numpy-arrays (og flerdimensjonale numpy-arrays generelt) er litt vanskelig, men det finnes ganske mange smarte funksjoner for det. Det enkleste er å aksessere enkeltelementer. Dette kan gjøres på to måter:

In [ ]:
import numpy as np

array = np.array([[7, 3.14, 5, 8],
                 [3, 9, 7 ,13],
                 [4, 5, 2.73, 9]])
print(array[2, 2]) # måte 1
print(array[2][2]) # måte 2


Grunnen til at den andre måten over fungerer er at vi først aksesserer en rad med den første hakeparantesen for så å aksessere elementet i raden med den andre hakeparantesen. Man kan altså aksessere en rad av en array med kun et sett med hakeparenteser som i eksempelet under. Kjør koden under og se hva som skjer.

In [ ]:
import numpy as np

array = np.array([[7, 3.14, 5, 8],
                 [3, 9, 7 ,13],
                 [4, 5, 2.73, 9]])
print(array[2]) # Aksessering av rad

I tillegg er det mulig å utføre slice-operasjoner på arrays, noe som kan være veldig nyttig. Slicing er et svært kraftig verktøy som lar deg aksessere hvilken som helst *sub-del* av tabellen.

***Se på eksemplene under og se om du skjønner hva som skjer. Endre gjerne på eksemplene og kjør på nytt***

In [ ]:
import numpy as np

array = np.array([[7, 3.14, 5, 8],
                 [3, 9, 7 ,13],
                 [4, 5, 2.73, 9]])

# obs: eksempel 1, 2 og 3 aksesserer kun rader
print("----------eks1----------\n")
print(array[:])

print("\n----------eks2----------\n")
print(array[:2])

print("\n----------eks3----------\n")
print(array[1:])

print("\n----------eks4----------\n")
print(array[1:3, 1:3])

print("\n----------eks5----------\n")
print(array[:, :2])

print("\n----------eks6----------\n")
print(array[:, 0]) # Aksessering av enkeltkolonne. OBS: Dette blir en endimensjonal numpy-array

En liten fallgruve som det er lett å gå i her er at slicing med numpy-arrays ikke lager nye arrays. Man bare oppretter nye pekere til samme data. Dette vises best med et eksempel.

***Hva tror du skjer under? Kjør koden og test det ut***

In [ ]:
import numpy as np

a = np.array([[2,2],
              [2,2]])

b = a[0] # Den første raden i a
b[0] = 0
b[1] = 0
print(b)
print("---------")
print(a)

Som du kanskje la merke til endrer nå `a` seg selv om vi kun gjør endringer på `b`. Dette var jo litt dumt. Prøv å bytte ut: `b = a[0]` med `b = a[0].copy()` over og se om det hjelper. Dette burde lage en ny kopi av dataene.

Nå har vi sett på det meste som omhandler aksessering av todimensjonale numpy-arrays. Det finnes også en metode som heter *fancy indexing*, men denne går vi ikke gjennom her. Du får heller søke opp fancy indexing selv på google hvis det høres spennende ut.

## Appending til todimensjonale numpy-arrays

Det er mulig å legge en array til annen array med funksjonen `np.append(array1, array2)`. Denne funksjonen vil returnere en ny array. Dersom du sender tabeller inn i append-funksjonen vil den flate ut tabellene og lage en lang endimensjonal array.

Der som vi i stedet ønsker å legge til en rad eller kolonne (eller flere rader og kolonner) må vi ha med ekstra-argumentet `axis` som bestemmer i hvilken retning arrayen skal appendes. I disse tilfellene er det viktig at dimensjonene er riktige. Hvis dette var litt uklart kommer det en rekke eksempler under.

***Kjør koden under og se om du skjønner hva som skjer***

In [ ]:
import numpy as np

a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

b = [[1, 2, 3]] # obs: to par med hakeparenteser

c = [[1],
     [2],
     [3]]

d = [[1, 2, 3],
     [4, 5, 6]]

e = [[1, 2],
     [3, 4],
     [5, 6]]

print("----------uten axis-----------")
print(np.append(a, b))

print("--------med axis (rad)--------")
print(np.append(a, b, axis=0)) # 0 er rad-aksen

print("------med axis (kolonne)------")
print(np.append(a, c, axis=1)) # 1 er kolonne-aksen

print("----med axis (flere rader)----")
print(np.append(a, d, axis=0))
     
print("--med axis (flere kolonner)---")
print(np.append(a, e, axis=1))

Her er det viktig å huske på at begge tabellene må ha like mange dimensjoner dersom du skal bruke `axis`. Hvis du prøver å legge sammen en tabell med en endimensjonal array (med `axis`) får du en error. 

## Nyttige funksjoner med todimensjonale numpy-arrays

Noe som er veldig nyttig med numpy-arrays er at de kommer med en haug med nyttige funksjoner. Det er for eksempel mulig å transponere en matrise (speile den om diagonalen) som under (matrise er et fancy navn for tabell). Transponering får dere bruk for i matte 3.

***Test det ut selv under:***

In [ ]:
import numpy as np

array = np.array([[7, 3.14, 5, 8],
                 [3, 9, 7 ,13],
                 [4, 5, 2.73, 9]])

print(np.transpose(array))

Det er også mulig å gjøre regneoperasjoner med todimensjonale arrays. Dette kan gjøres likt som med endimensjonale arrays som i eksemplene under:

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print(a + 1) # Plusser 1 på alle elementene i tabellen
print("\n-------------\n")
print(np.sqrt(a)) # Tar roten av alle elementene
print("\n-------------\n")
print(a + b) # Plusser sammen to tabeller. Disse må ha lik form

Det som er litt spennende er at siden vi nå har økt med en dimensjon er det også mulig å slå sammen en 2-dimensjonal numpy-array med en endimensjonal numpy-array. Dette er nok best å vise med et eksempel.

***Kjør koden under og se om du forstår hva som skjer***

In [ ]:
import numpy as np

a = np.array([[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])

b = np.array([1, 2, 3])

c = np.reshape(b, (3, 1)) # Gjør om b slik at den blir en kolonne i stedet for en rad.

# for å lage c fra scratch kunne vi skrevet som under
# c = np.array([[1], 
#               [2], 
#               [3]])

print(a + b)
print("-----------")
print(a + c)

Som du ser her må altså den endimensjonale arrayen være lik tabellen i en dimensjon og være 1 i den andre dimensjonen. Denne blir da kopiert inn så mange ganger det går i enten den ene eller andre retningen. Dette kan være veldig nyttig i en del tilfeller.

Det er også mulig å lage en sannhetsmatrise (eller boolsk matrise) fra en vanlig matrise slik som i eksemplene under. Her får vi da en sannhetsmatrise etter hvilke elementer som oppfyller betingelsen.

***Kjør eksempelet under og se om du skjønner hvordan det fungerer***

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
print("------------------")
print(a >= 5) # Større eller lik 5
print("------------------")
print(a < 8) # Mindre enn 8
print("------------------")
print(np.logical_and(a >= 5, a < 8)) # Både mer eller lik 5 og mindre enn 8

Som du ser får vi matriser etter hvilke elementer i den originale matrisen som oppfyller betingelsene.

En måte boolske matriser kan brukes på er at vi kan gange en matrise med en boolsk matrise. Vi får da med alle elementene på posisjoner hvor vi har True i den boolske matrisen, mens resten blir 0. Kjør eksempelet under:

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
print("------------------")
boolsk = a >= 5
print(boolsk)
print("------------------")
print(a * boolsk)

Dette har vært en liten oversikt over hva som er mulig med todimensjonale matriser. Det som er litt gøy er at veldig mange av de samme konseptene kan brukes videre når man går over til 3 dimensjoner. Det finnes også mange funksjoner i numpy som vi ikke har gått gjennom, for eksempel matrisemultiplikasjon og utregning av determinanter som kan være nyttig til matte 3.

## Eksempel på plotting med todimensjonale numpy-arrays

Det er mulig å bruke todimensjonale arrays til plotting av data. Her kan du for eksempel plotte en funksjon som finner en z-verdi ved hjelp av en x-verdi og en y-verdi. Dette kan plottes som et bilde hvor z-verdien blir en gråfarge. Med dette kan vi for eksempel plotte grafen for $z = \sqrt{x^2 + y^2}$. Her kan vi bruke funksjonen `np.meshgrid` som gir oss et sett med x-verdier og et sett med y-verdier, samt funksjonen `plt.imshow()` for å lage et bilde.

***Kjør eksempelet under og sjekk om du skjønner hva som skjer***

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Lager en array points på formen [-5.0, -4.9, -4.8 ... 4.8, 4.9]
points = np.arange(-5, 5, 0.1)

# Lager x-verdier og y-verdier
xs, ys = np.meshgrid(points, points)

# Printer ut x- og y-verdiene slik at du kan se hvordan disse ser ut
print("----------------xs-----------------\n")
print(xs)
print("\n----------------ys-----------------\n")
print(ys)

# Lager z-verdiene ved hjelp av x-verdiene og y-verdiene etter formelen 
# beskrevet over
zs = np.sqrt(xs ** 2 + ys ** 2)

# Printer ut z-verdiene slik at du kan se hvordan de ser ut
print("\n----------------zs-----------------\n")
print(zs)

# Plotter z-verdiene. cmap=plt.cm.gray må være med siden vi skal ha gråtoner,
# extent gir oss riktige x- og y-verdier. (siden vi gå fra -5 til 5 på begge
# akser)
plt.imshow(zs, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])

# Legger til en fargeskala på høyresiden slik at man kan se hva slags farge
# som korresponderer til hvilket tall
plt.colorbar()

# Viser plottet
plt.show()

Merk at tabellene ikke skrives ut i sin helhet ettersom de er ganske store.

# Eksempler på oppgaver med todimensjonale numpy-arrays

## Oppgave 1

Bruk funksjonene `np.arange()`, `np.reshape()` og `np.transpose()` for å lage og printe denne tabellen:
```python
[[ 1,  6, 11],
 [ 2,  7, 12],
 [ 3,  8, 13],
 [ 4,  9, 14],
 [ 5, 10, 15]]
```

**Hint:** denne kan gjøres på en linje

***Skriv koden din i kodeblokken under:***

In [ ]:
import numpy as np
# Skriv koden din under


## Oppgave 2

Du får opgitt en todimensjonal numpy-array under. Bruk slicing til å hente ut disse 4 numpy-arrayene fra den opprinnelige arrayen `a`:
```python
# array 1:
[[1 8]
 [3 9]]

# array 2:
[5 7 6]

# array 3:
[[9 4]
 [7 6]]

# array 4:
[2 4 6]
```

Du skal altså bruke syntaksen `a[<putt et eller annet her>]`

***Skriv koden din i kodeblokken under***

In [ ]:
import numpy as np
a = np.array([[1, 8, 2],
              [3, 9, 4],
              [5, 7, 6]])
# Skriv koden din under:


## Oppgave 3

Under har vi laget en tabell. Denne skal du endre med å bruke funksjonen `np.append` (med `axis`-argumentet). Først skal du legge til en ny *rad* til tabellen med verdiene 8,9 og 6. Deretter skal du legge til en ny *kolonne* til den nye tabellen med verdiene 4, 8 og 7. Tabellen du skal ende opp med skal altså se slik ut:

>```python
[[5 6 9 4]
 [3 4 7 8]
 [8 9 6 7]]
```

***Skriv koden i kodeblokken under***

In [ ]:
import numpy as np
a = [[5, 6, 9],
     [3, 4, 7]]
# Skriv koden din under


## Oppgave 4

Nå skal du plotte et bilde av funksjonen $z = sin(\sqrt{x^2 + y^2})$. Denne skal plottes fra -50 til 50 i både x-retningen og y-retningen, og du skal bruke funksjonene `np.meshgrid` og `plt.imshow`.

**Hint:** Du kan bruke mye av koden fra ploteksempelet tidligere

***Skriv koden i kodeblokken under:***

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# Skriv koden din under her


# Fasiter

In [ ]:
print("Oppgave 1:")
import numpy as np

print(np.arange(1, 16, 1).reshape(3, 5).transpose())


print("\nOppgave 2:")
import numpy as np
a = np.array([[1, 8, 2],
              [3, 9, 4],
              [5, 7, 6]])

print(a[:2, :2])
print("\n----------\n")
print(a[2])
print("\n----------\n")
print(a[1:, 1:])
print("\n----------\n")
print(a[:, 2])


print("\nOppgave 3:")
import numpy as np
a = [[5, 6, 9],
     [3, 4, 7]]

b = [[8, 9, 6]]

a = np.append(a, b, axis=0)

c = [[4],
     [8],
     [7]]

a = np.append(a, c, axis=1)

print(a)


print("\nOppgave 4:")
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

points = np.arange(-50, 50, 0.1)

xs, ys = np.meshgrid(points, points)
z = np.sin(np.sqrt(xs**2 + ys**2))

plt.imshow(z, cmap=plt.cm.gray, extent=[-50,50,-50,50])

plt.colorbar()
plt.show()